const PRODUCE_IMAGES = {
	"a-choy": {
		name: "A-Choy",
		chinese: "",
		path: "images/produce/a-choy.jpg",
		thumbnail: "images/produce/a-choy_thumb.jpg",
		category: "",
		source: ["Canada", "Florida"],
		alt: "",
	},
	"american_okra": {
		name: "American Okra",
		chinese: "",
		path: "images/produce/american_okra.jpg",
		thumbnail: "images/produce/american_okra_thumb.jpg",
		category: "",
		source: ["Honduras"],
		alt: "",
	},
	"baby_bok_choy": {
		name: "Baby Bok Choy",
		chinese: "",
		path: "images/produce/baby_bok_choy.jpg",
		thumbnail: "images/produce/baby_bok_choy_thumb.jpg",
		category: "",
		source: ["Canada"],
		alt: "",
	},
	"banana_flower": {
		name: "Banana Flower",
		chinese: "香蕉花",
		path: "images/produce/banana_flower.jpg",
		thumbnail: "images/produce/banana_flower_thumb.jpg",
		category: "",
		source: ["Mexico", "Florida"],
		alt: "",
	},
	"cabbage": {
		name: "Cabbage",
		chinese: "",
		path: "images/produce/cabbage.jpg",
		thumbnail: "images/produce/cabbage_thumb.jpg",
		category: "",
		source: ["Canada", "Florida"],
		alt: "",
	},
	"cayan": {
		name: "Cayan",
		chinese: "",
		path: "images/produce/cayan.jpg",
		thumbnail: "images/produce/cayan_thumb.jpg",
		category: "",
		source: ["Florida"],
		alt: "",
	},
	"chapoo_(e-lert)": {
		name: "Chapoo (E-lert)",
		chinese: "",
		path: "images/produce/chapoo.jpg",
		thumbnail: "images/produce/chapoo_thumb.jpg",
		category: "",
		source: ["Florida"],
		alt: "",
	},
	"chayote": {
		name: "Chayote",
		chinese: "佛手瓜",
		path: "images/produce/chayote.jpg",
		thumbnail: "images/produce/chayote_thumb.jpg",
		category: "",
		source: ["Costa Rica"],
		alt: "",
	},
	"chinese_bitter_melon": {
		name: "Chinese Bitter Melon",
		chinese: "苦瓜",
		path: "images/produce/chinese_bitter_melon.jpg",
		thumbnail: "images/produce/chinese_bitter_melon_thumb.jpg",
		category: "",
		source: ["Florida", "Honduras"],
		alt: "",
	},
	"chinese_celery": {
		name: "Chinese Celery",
		chinese: "",
		path: "images/produce/chinese_celery.jpg",
		thumbnail: "images/produce/chinese_celery_thumb.jpg",
		category: "",
		source: ["Canada"],
		alt: "",
	},
	"chinese_eggplant": {
		name: "Chinese Eggplant",
		chinese: "中茄",
		path: "images/produce/chinese_eggplant.jpg",
		thumbnail: "images/produce/chinese_eggplant_thumb.jpg",
		category: "",
		source: ["Honduras"],
		alt: "",
	},
	"chinese_lo_bok": {
		name: "Chinese Lo Bok",
		chinese: "",
		path: "images/produce/chinese_lo_bok.jpg",
		thumbnail: "images/produce/chinese_lo_bok_thumb.jpg",
		category: "",
		source: ["Canada"],
		alt: "",
	},
	"chinese_okra": {
		name: "Chinese Okra",
		chinese: "",
		path: "images/produce/chinese_okra.jpg",
		thumbnail: "images/produce/chinese_okra_thumb.jpg",
		category: "",
		source: ["Florida"],
		alt: "",
	},
	"chive_flower": {
		name: "Chive Flower",
		chinese: "",
		path: "images/produce/chive_flower.jpg",
		thumbnail: "images/produce/chive_flower_thumb.jpg",
		category: "",
		source: ["Honduras"],
		alt: "",
	},
	"cilantro": {
		name: "Cilantro",
		chinese: "",
		path: "images/produce/cilantro.jpg",
		thumbnail: "images/produce/cilantro_thumb.jpg",
		category: "",
		source: ["Canada", "Florida"],
		alt: "",
	},
	"culantro": {
		name: "Culantro",
		chinese: "",
		path: "images/produce/culantro.jpg",
		thumbnail: "images/produce/culantro_thumb.jpg",
		category: "",
		source: ["Costa Rica"],
		alt: "",
	},
	"dragon_fruit": {
		name: "Dragon Fruit",
		chinese: "",
		path: "images/produce/dragon_fruit.jpg",
		thumbnail: "images/produce/dragon_fruit_thumb.jpg",
		category: "",
		source: ["Florida"],
		alt: "",
	},
	"flat_valor": {
		name: "Flat Valor",
		chinese: "",
		path: "images/produce/flat_valor.jpg",
		thumbnail: "images/produce/flat_valor_thumb.jpg",
		category: "",
		source: ["Florida"],
		alt: "",
	},
	"fuzzy_squash": {
		name: "Fuzzy Squash",
		chinese: "毛瓜",
		path: "images/produce/fuzzy_squash.jpg",
		thumbnail: "images/produce/fuzzy_squash_thumb.jpg",
		category: "",
		source: ["Honduras"],
		alt: "",
	},
	"gai_lan": {
		name: "Gai Lan",
		chinese: "",
		path: "images/produce/gai_lan.jpg",
		thumbnail: "images/produce/gai_lan_thumb.jpg",
		category: "",
		source: ["Canada", "Mexico", "Florida", "California"],
		alt: "",
	},
	"garlic": {
		name: "Garlic",
		chinese: "",
		path: "images/produce/garlic.jpg",
		thumbnail: "images/produce/garlic_thumb.jpg",
		category: "",
		source: ["China"],
		alt: "",
	},
	"ginger": {
		name: "Ginger",
		chinese: "姜",
		path: "images/produce/ginger.jpg",
		thumbnail: "images/produce/ginger_thumb.jpg",
		category: "",
		source: ["Canada"],
		alt: "",
	},
	"gobo": {
		name: "Gobo",
		chinese: "",
		path: "images/produce/gobo.jpg",
		thumbnail: "images/produce/gobo_thumb.jpg",
		category: "",
		source: ["China"],
		alt: "",
	},
	"green_mango": {
		name: "Green Mango",
		chinese: "",
		path: "images/produce/green_mango.jpg",
		thumbnail: "images/produce/green_mango_thumb.jpg",
		category: "",
		source: ["Puerto Rico", "Florida"],
		alt: "",
	},
	"green_papaya": {
		name: "Green Papaya",
		chinese: "",
		path: "images/produce/green_papaya.jpg",
		thumbnail: "images/produce/green_papaya_thumb.jpg",
		category: "青木瓜",
		source: ["Guatemala", "Florida"],
		alt: "",
	},
	"habanero": {
		name: "Habanero",
		chinese: "",
		path: "images/produce/habanero.jpg",
		thumbnail: "images/produce/habanero_thumb.jpg",
		category: "",
		source: ["Honduras", "Dominican Republic"],
		alt: "",
	},
	"indian_bitter_melon": {
		name: "Indian Bitter Melon",
		chinese: "印度苦瓜",
		path: "images/produce/indian_bitter_melon.jpg",
		thumbnail: "images/produce/indian_bitter_melon_thumb.jpg",
		category: "",
		source: ["Honduras", "Florida"],
		alt: "",
	},
	"indian_eggplant": {
		name: "Indian Eggplant",
		chinese: "",
		path: "images/produce/indian_eggplant.jpg",
		thumbnail: "images/produce/indian_eggplant_thumb.jpg",
		category: "",
		source: ["Florida"],
		alt: "",
    },
    "indian_okra": {
		name: "Indian Okra",
		chinese: "",
		path: "",
		thumbnail: "",
		category: "",
		source: ["Honduras"],
		alt: "",
	},
	"japanese_yam": {
		name: "Japanese Yam",
		chinese: "",
		path: "images/produce/japanese_yam.jpg",
		thumbnail: "images/produce/japanese_yam_thumb.jpg",
		category: "",
		source: ["California"],
		alt: "",
	},
	"jicama": {
		name: "Jicama",
		chinese: "沙葛",
		path: "images/produce/jicama.jpg",
		thumbnail: "images/produce/jicama_thumb.jpg",
		category: "",
		source: ["Mexico"],
		alt: "",
	},
	"kabocha": {
		name: "Kabocha",
		chinese: "",
		path: "images/produce/kabocha.jpg",
		thumbnail: "images/produce/kabocha_thumb.jpg",
		category: "",
		source: ["Mexico", "Florida"],
		alt: "",
	},
	"kohlrabi": {
		name: "Kohlrabi",
		chinese: "",
		path: "images/produce/kohlrabi.jpg",
		thumbnail: "images/produce/kohlrabi_thumb.jpg",
		category: "",
		source: ["Canada", "Florida"],
		alt: "",
	},
	"lemongrass": {
		name: "Lemongrass",
		chinese: "香茅",
		path: "images/produce/lemongrass.jpg",
		thumbnail: "images/produce/lemongrass_thumb.jpg",
		category: "",
		source: ["California"],
		alt: "",
	},
	"long_bean": {
		name: "Long Bean",
		chinese: "",
		path: "images/produce/long_bean.jpg",
		thumbnail: "images/produce/long_bean_thumb.jpg",
		category: "",
		source: ["Florida"],
		alt: "",
	},
	"long_squash": {
		name: "Long Squash",
		chinese: "葫芦瓜",
		path: "images/produce/long_squash.jpg",
		thumbnail: "images/produce/long_squash_thumb.jpg",
		category: "",
		source: ["Honduras"],
		alt: "",
	},
	"longan": {
		name: "Longan",
		chinese: "龙眼",
		path: "images/produce/longan.jpg",
		thumbnail: "images/produce/longan_thumb.jpg",
		category: "",
		source: ["Florida"],
		alt: "",
	},
	"malanga_edo": {
		name: "Malanga Edo",
		chinese: "小芋头",
		path: "images/produce/malanga_edo.jpg",
		thumbnail: "images/produce/malanga_edo_thumb.jpg",
        category: "",
        source: ["Costa Rica"],
		alt: "",
	},
	"mango_valencia": {
		name: "Valencia Pride Mango",
		chinese: "",
		path: "images/produce/mango.jpg",
		thumbnail: "images/produce/mango_thumb.jpg",
        category: "",
        source: ["Florida"],
		alt: "",
	},
	"montoy": {
		name: "Montoy",
		chinese: "木耳菜",
		path: "images/produce/montoy.jpg",
		thumbnail: "images/produce/montoy_thumb.jpg",
        category: "",
        source: ["Florida"],
		alt: "",
	},
	"napa": {
		name: "Napa",
		chinese: "",
		path: "images/produce/napa.jpg",
		thumbnail: "images/produce/napa_thumb.jpg",
        category: "",
        source: ["Canada", "Florida"],
		alt: "",
	},
	"passion_fruit": {
		name: "Passion Fruit",
		chinese: "",
		path: "images/produce/passion_fruit.jpg",
		thumbnail: "images/produce/passion_fruit_thumb.jpg",
        category: "",
        source: ["Florida"],
		alt: "",
	},
	"potato_leaf": {
		name: "Potato Leaf",
		chinese: "番薯叶",
		path: "images/produce/potato_leaf.jpg",
		thumbnail: "images/produce/potato_leaf_thumb.jpg",
        category: "",
        source: ["Florida"],
		alt: "",
	},
	"pumpkin": {
		name: "Pumpkin",
		chinese: "南瓜",
		path: "images/produce/pumpkin.jpg",
		thumbnail: "images/produce/pumpkin_thumb.jpg",
        category: "",
        source: ["Panama", "Florida"],
		alt: "",
	},
	"rambutan": {
		name: "Rambutan",
		chinese: "红毛丹",
		path: "images/produce/rambutan.jpg",
		thumbnail: "images/produce/rambutan_thumb.jpg",
        category: "",
        source: ["Honduras", "Guatemala"],
		alt: "",
	},
	"shallot": {
		name: "Shallot",
		chinese: "紅葱头",
		path: "images/produce/shallot.jpg",
		thumbnail: "images/produce/shallot_thumb.jpg",
        category: "",
        source: ["China"],
		alt: "",
	},
	"shanghai_bok_choy": {
		name: "Shanghai Bok Choy",
		chinese: "上海白",
		path: "images/produce/shanghai_bok_choy.jpg",
		thumbnail: "images/produce/shanghai_bok_choy_thumb.jpg",
        category: "",
        source: ["Canada"],
		alt: "",
	},
	"snow_peas": {
		name: "Snow Peas",
		chinese: "雪豆",
		path: "images/produce/snow_peas.jpg",
		thumbnail: "images/produce/snow_peas_thumb.jpg",
        category: "",
        source: ["Guatemala"],
		alt: "",
	},
	"sugar_apple": {
		name: "Sugar Apple",
		chinese: "",
		path: "images/produce/sugar_apple.jpg",
		thumbnail: "images/produce/sugar_apple_thumb.jpg",
        category: "",
        source: ["Florida"],
		alt: "",
	},
	"sugar_snap": {
		name: "Sugar Snap",
		chinese: "甜豆",
		path: "images/produce/sugar_snap.jpg",
		thumbnail: "images/produce/sugar_snap_thumb.jpg",
        category: "",
        source: ["Guatemala"],
		alt: "",
	},
	"thai_banana": {
		name: "Thai Banana",
		chinese: "",
		path: "images/produce/thai_banana.jpg",
		thumbnail: "images/produce/thai_banana_thumb.jpg",
        category: "",
        source: ["Honduras", "Mexico"],
		alt: "",
	},
	"thai_basil": {
		name: "Thai Basil (Holopa)",
		chinese: "九层塔",
		path: "images/produce/thai_basil.jpg",
		thumbnail: "images/produce/thai_basil_thumb.jpg",
        category: "",
        source: ["Florida"],
		alt: "",
    },
    "thai_coco": {
		name: "Thai Coco",
		chinese: "椰子",
		path: "images/produce/thai_coco.jpg",
		thumbnail: "images/produce/thai_coco_thumb.jpg",
		category: "",
		source: ["Thailand"],
		alt: "",
	},
	"thai_eggplant": {
		name: "Thai Eggplant",
		chinese: "",
		path: "images/produce/thai_eggplant.jpg",
		thumbnail: "images/produce/thai_eggplant_thumb.jpg",
        category: "",
        source: ["Honduras"],
		alt: "",
	},
	"thai_ginger_(galanga)": {
		name: "Thai Ginger",
		chinese: "泰姜",
		path: "images/produce/thai_ginger_(galanga).jpg",
		thumbnail: "images/produce/thai_ginger_(galanga)_thumb.jpg",
        category: "",
        source: ["Florida"],
		alt: "",
	},
	"thai_green_hot_pepper": {
		name: "Thai Green Hot Pepper",
		chinese: "泰国椒",
		path: "images/produce/thai_green_hot_pepper.jpg",
		thumbnail: "images/produce/thai_green_hot_pepper_thumb.jpg",
        category: "",
        source: ["Dominican Republic"],
		alt: "",
	},
	"thai_okra": {
		name: "Thai Okra",
		chinese: "丝瓜",
		path: "images/produce/thai_okra.jpg",
		thumbnail: "images/produce/thai_okra_thumb.jpg",
        category: "",
        source: ["Honduras"],
		alt: "",
	},
	"thai_red_hot_pepper": {
		name: "Thai Red Hot Pepper",
		chinese: "",
		path: "images/produce/thai_red_hot_pepper.jpg",
		thumbnail: "images/produce/thai_red_hot_pepper_thumb.jpg",
        category: "",
        source: ["Dominican Republic"],
		alt: "",
	},
	"tong_hao": {
		name: "Tong Hao",
		chinese: "",
		path: "images/produce/tong_hao.jpg",
		thumbnail: "images/produce/tong_hao_thumb.jpg",
        category: "",
        source: ["Canada", "Florida"],
		alt: "",
	},
	"tun": {
		name: "Tun",
		chinese: "芋梗",
		path: "images/produce/tun.jpg",
		thumbnail: "images/produce/tun_thumb.jpg",
        category: "",
        source: ["Florida"],
		alt: "",
	},
	"wawa": {
		name: "Wawa",
		chinese: "",
		path: "images/produce/wawa.jpg",
		thumbnail: "images/produce/wawa_thumb.jpg",
        category: "",
        source: ["Canada", "Flordia"],
		alt: "",
	},
	"wax_apple": {
		name: "Wax Apple",
		chinese: "",
		path: "images/produce/wax_apple.jpg",
		thumbnail: "images/produce/wax_apple_thumb.jpg",
        category: "",
        source: ["Florida"],
		alt: "",
	},
	"winter_melon": {
		name: "Winter Melon",
		chinese: "冬瓜",
		path: "images/produce/winter_melon.jpg",
		thumbnail: "images/produce/winter_melon_thumb.jpg",
        category: "",
        source: ["Florida"],
		alt: "",
	},
	"yuca": {
		name: "Yuca",
		chinese: "木薯",
		path: "images/produce/yuca.jpg",
		thumbnail: "images/produce/yuca_thumb.jpg",
        category: "",
        source: ["Costa Rica"],
		alt: "",
	},
	"yuca_leaf": {
		name: "Yuca Leaf",
		chinese: "",
		path: "images/produce/yuca_leaf.jpg",
		thumbnail: "images/produce/yuca_leaf_thumb.jpg",
        category: "",
        source: ["Florida"],
		alt: "",
	}
};